### ISSUE TITLE
Add Basic concepts of functional JS

### ISSUE THREAD

**Issue by jmrchelani** [gdscmuet/learn-js#1]
Self explanatory, add the basic concepts of functional JS.. 

Topics to be covered:
1. Basic I/O
2. Loops and Control Structure
3. Functions, Methods and basic data types etc

**Comment by Malhar-Soomro** [comment]
@jmrchelani Assign me this issue.

**Comment by jmrchelani** [comment]
Assigned, you can contribute on this one!
