### ISSUE TITLE
Add basic concepts of OOP in JS

### ISSUE THREAD

**Issue by jmrchelani** [gdscmuet/learn-js#2]
Self explanatory, need to add object oriented programming concepts of js

**Comment by iamzaidsoomro** [comment]
@Algeo3603 just fork the repo and create new folder in it named as OOP-Concepts-JavaScript

**Comment by Algeo3603** [comment]
Can you assign this issue to me? I'd like to add some good resources for OOPS in JavaScript.

**Comment by iamzaidsoomro** [comment]
@Algeo3603 Please add the coding example instead of only sharing links in the markdown file.
